### ISSUE TITLE
构建执行pack:prod命令报错

### ISSUE THREAD

**Issue by lovelytan** [opensumi/app-desktop#1]
1. 执行`yarn run pack:prod`报错，提示`scripts/pack.js`中缺少`product.json`文件
2. 自行补齐`scripts/pack.js`文件并添加`productName`字段后再次执行报错`UnhandledPromiseRejectionWarning: Error: Invalid version: "{{auto-fill-version}}"`，使用的node版本为`14.19.0`，下面是报错信息

```bash

(node:54596) UnhandledPromiseRejectionWarning: Error: Invalid version: "{{auto-fill-version}}"
    at fixVersionField (/Users/xxx/Projects/opensumi/app-desktop/node_modules/app-builder-lib/src/util/normalizePackageData.ts:146:13)
    at Object.normalizePackageData (/Users/xxx/Projects/opensumi/app-desktop/node_modules/app-builder-lib/src/util/normalizePackageData.ts:7:5)
    at Object.readPackageJson (/Users/xxx/Projects/opensumi/app-desktop/node_modules/app-builder-lib/src/util/packageMetadata.ts:15:3)
    at Packager.readProjectMetadataIfTwoPackageStructureOrPrepacked (/Users/xxx/Projects/opensumi/app-desktop/node_modules/app-builder-lib/src/packager.ts:399:16)
    at Packager.build (/Users/xxx/Projects/opensumi/app-desktop/node_modules/app-builder-lib/src/packager.ts:328:24)
    at Object.executeFinally (/Users/xxx/Projects/opensumi/app-desktop/node_modules/builder-util/src/promise.ts:12:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by yantze** [comment]
已修复， pull 一下最新的代码
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/2226423/184271952-da3b7b26-bac7-4e05-9fe4-62b264586612.png">

**Comment by naduohua** [comment]
> 已修复， pull 一下最新的代码 <img alt="image" width="1200" src="https://user-images.githubusercontent.com/2226423/184271952-da3b7b26-bac7-4e05-9fe4-62b264586612.png">

麻烦再看看，更新后执行`build`命令报错

```bash

[webpack-cli] Failed to load '/Users/xxx/Projects/opensumi/app-desktop/build/webpack.main.config.ts' config
[webpack-cli] build/webpack.base.config.ts:66:7 - error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type '"..." | ResolvePluginInstance'.
  Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
    Types of property 'apply' are incompatible.
      Type '(resolver: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void'.
        Types of parameters 'resolver' and 'resolver' are incompatible.
          Type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver' is not assignable to type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
            The types of 'options.plugins' are incompatible between these types.
              Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
                Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
                  Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
                    Type '{ apply: (arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
                      Types of property 'apply' are incompatible.
                        Type '(arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
                          Types of parameters 'arg0' and 'arg0' are incompatible.
                            Type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver'.
                              Types of property 'options' are incompatible.
                                Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.

66       new TsconfigPathsPlugin({
         ~~~~~~~~~~~~~~~~~~~~~~~~~
67         configFile: tsConfigPath,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68       }),
   ~~~~~~~~

  node_modules/webpack/types.d.ts:9620:2
    9620  extensionAlias: ExtensionAliasOption[];
          ~~~~~~~~~~~~~~
    'extensionAlias' is declared here.

[webpack-cli] Failed to load '/Users/xxx/Projects/opensumi/app-desktop/build/webpack.browser.config.ts' config

```

**Comment by lovelytan** [comment]
@yantze  麻烦再看一下，更新后`build`报错。


```bash
[webpack-cli] Failed to load '/Users/xxx/Projects/opensumi/app-desktop/build/webpack.main.config.ts' config
[webpack-cli] build/webpack.base.config.ts:66:7 - error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type '"..." | ResolvePluginInstance'.
  Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
    Types of property 'apply' are incompatible.
      Type '(resolver: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void'.
        Types of parameters 'resolver' and 'resolver' are incompatible.
          Type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver' is not assignable to type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
            The types of 'options.plugins' are incompatible between these types.
              Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
                Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
                  Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
                    Type '{ apply: (arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
                      Types of property 'apply' are incompatible.
                        Type '(arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
                          Types of parameters 'arg0' and 'arg0' are incompatible.
                            Type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/Users/xxx/Projects/opensumi/app-desktop/node_modules/webpack/types").Resolver'.
                              Types of property 'options' are incompatible.
                                Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.

66       new TsconfigPathsPlugin({
         ~~~~~~~~~~~~~~~~~~~~~~~~~
67         configFile: tsConfigPath,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68       }),
   ~~~~~~~~

  node_modules/webpack/types.d.ts:9620:2
    9620  extensionAlias: ExtensionAliasOption[];
          ~~~~~~~~~~~~~~
    'extensionAlias' is declared here.

[webpack-cli] Failed to load '/Users/xxx/Projects/opensumi/app-desktop/build/webpack.browser.config.ts' config
```

**Comment by yantze** [comment]
已修复 拉一下代码
